Repository GroceriStar/sd, pull requests merged in 2019-05, with the labels that each got.

#295 readme.md changes
  .gitignore
  README.md
Labels: ternovka

#304 README.md edition
  README.md
  docs/Readme.md
  generator/projects/ChickenKyiv/test/chickenKyiv.test.js
  generator/projects/ChickenKyiv/test/chickenKyiv.teszt.js
  package.json
  src/data/MeasurementSystem/measurementSystem.json
  src/data/MeasurementUnits/measurementUnits.json
  src/data/UsersGrocery/usersGrocery.json
  src/data/__tests__/nutritionalAttributes.test.js
  src/data/jsonlint.config.js
Labels: tests

#358 Update allergy.test.js
  src/data/__tests__/allergy.test.js
Labels: in-progress

#393 Renaming some json files and moving tests
  files.js
  jsonlint.config.js
  package.json
  src/data/CookingTimes/cookingTimes.json
  src/data/DietAndHealthLabel/dietAndHealthLabel.json
  src/data/Gallon/gallon.json
  src/data/HalfCup/halfCup.json
  src/data/Pint/pint.json
  src/data/Quart/quart.json
  src/data/QuaterCup/quaterCup.json
  src/data/Tablespoon/tablespoon.json
  src/data/Teaspoon/teaspoon.json
  tests/projects/ChickenKyiv/chickenKyiv.teszt.js
  tests/projects/GS-Loopback/loopback.teszt.js
  tests/projects/GraphQL/graphQL.teszt.js
  tests/projects/GroceriStar/groceristar.test.js
  tests/projects/MealCalendar/mealCalendar.teszt.js
  tests/projects/Search/search.teszt.js
  tests/projects/Showcase/showcase.teszt.js
  tests/projects/UnitConvertion/files.teszt.js
Labels: in-progress

#416 upd
  package.json
  src/data/CookingTimes/cookingTimes.json
  tests/cookingTimes.test.js
  tests/cup1.test.js
  tests/cup1_8.test.js
  tests/cup3_4.test.js
  tests/gallon.test.js
Labels: in-progress
